// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQuvEBFHA76J8vgiQdDARNWaf3ndN6fGA',
    appId: '1:578780347386:web:930d357883bc01be06c243',
    messagingSenderId: '578780347386',
    projectId: 'ingressoaquii-eb010',
    authDomain: 'ingressoaquii-eb010.firebaseapp.com',
    storageBucket: 'ingressoaquii-eb010.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvBQCpAzvkL43WlQr9I8TtwE03vhu8elE',
    appId: '1:578780347386:android:e4f1189697bb8f2606c243',
    messagingSenderId: '578780347386',
    projectId: 'ingressoaquii-eb010',
    storageBucket: 'ingressoaquii-eb010.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT--5GdC_NSyKxuPERpyc6A7B9F4xvUbo',
    appId: '1:578780347386:ios:208759b5711c2a9e06c243',
    messagingSenderId: '578780347386',
    projectId: 'ingressoaquii-eb010',
    storageBucket: 'ingressoaquii-eb010.appspot.com',
    iosBundleId: 'com.example.ingressoAquii',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT--5GdC_NSyKxuPERpyc6A7B9F4xvUbo',
    appId: '1:578780347386:ios:e32f53f4521b27ae06c243',
    messagingSenderId: '578780347386',
    projectId: 'ingressoaquii-eb010',
    storageBucket: 'ingressoaquii-eb010.appspot.com',
    iosBundleId: 'com.example.ingressoAquii.RunnerTests',
  );
}
